spring.application.name=warehouse-system

# Database Configuration
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/werehouse
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#server.servlet.context-path=/warehouse

# JWT Configuration
jwt.secret=myVeryLongSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm1234567890
jwt.expiration=86400000

# SQL Initialization
#spring.sql.init.mode=always
#spring.sql.init.schema-locations=classpath:sql/schema.sql

